---
kind: pipeline
type: docker
name: default

steps:
  - name: Install dependanice 
    image: node:10.12.0-slim
    commands:
    - npm install
    - npm run build
    
  - name: build-docker-image
    image: docker:dind
    volumes:
    - name: dockersock
      path: /var/run
    commands:
      - docker build -t my-node-app:$DRONE_BUILD_NUMBER .
      - docker images

  - name: list-all-environment-variables
    image: alpine
    commands:
      - printenv

services:
  docker:
    image: docker:dind
    privileged: true
    command: [ '-H', 'unix:///drone/docker.sock' ]
volumes:
- name: dockersock
  temp: {}

